### ISSUE TITLE
Get rid of the pesky 'connection failed' popup in the UI

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#450] opened 2020-01-07 11:16 UTC
Every time I restart the backend during development I see this "Connection Failed" popup in the bottom-right corner of the web app. I then have to point my mouse to the tiny cross and click it to close the popup. It is too annoying, and happens every time. Instead, we could make this indicator smaller, and auto-hide it when connection resumes.

**Comment by rosik** [comment] 2020-01-07 12:54
Duplicate of #395

**Closed by rosik** 2020-01-07 12:54 UTC
