### ISSUE TITLE
Support other box options in stateboard

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#802] opened 2020-04-21 12:34 UTC
There are many other argparse options that may be useful in stateboard, i.e. logging, memtx, process management (see https://github.com/tarantool/cartridge/blob/master/cartridge/argparse.lua). Let's add them all to the stateboard.

**Comment by olegrok** [comment] 2020-04-21 17:25
Duplicate of https://github.com/tarantool/cartridge/issues/710

**Closed** 2020-04-24 15:12 UTC
