### ISSUE TITLE
Describe instance state machine in doc

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#564] opened 2020-02-10 15:33 UTC
Here is the draft [UML](https://www.planttext.com/?text=TPBDQiCm48JlUeebnq9UeOIO1Wg5Ga9FeGTXRMo1l2jMwvAyVMN7RVoNayJecvrXqIwf5MsRO4pj7G8sKM_WC9NYeteceru3Gf4fyQv2y9GjL2BaGn4QTfZDvvTls6vVuOjAfeklMa7tBnQzTE2Md35Zed_TCsjIiJ5wglPyDMR4Z_mVR5qUEdzy9wzl8Yp6t1jjvWE11OvOyWzA5avaOwfPDs3JCdiSzQJTOlnGaR3Kh1pQ41fCzJhNYKFRfMKWhiLZXMjGm8kkHwxHayp9yD5kssupHmwO_hR_K7gilqrxBQ7FY6AxJtDFctcUnEsGNFv_lm00), but it should be revised and described in more details

**Comment by NickVolynkin** [comment] 2021-03-19 09:28
Duplicate of https://github.com/tarantool/doc/issues/1538

**Closed by NickVolynkin** 2021-03-19 09:28 UTC
Labels: documentation
