### ISSUE TITLE
flaky test: `hotreload.vshard.test_rebalancer`

### ISSUE THREAD

**Issue by Steap2448** [tarantool/cartridge#1595] opened 2021-11-08 07:29 UTC
```
1) hotreload.vshard.test_rebalancer
.../work/cartridge/cartridge/test/hotreload/vshard_test.lua:194: expected: 2000, actual: 1500
stack traceback:
	.../work/cartridge/cartridge/test/hotreload/vshard_test.lua:194: in function 'retrying'
	.../work/cartridge/cartridge/test/hotreload/vshard_test.lua:192: in function 'hotreload.vshard.test_rebalancer'
	...
	[C]: in function 'xpcall'
```

[log.txt](https://github.com/tarantool/cartridge/files/7496062/log.txt)

**Comment by Steap2448** [comment] 2021-11-08 09:52
[logs_5216.zip](https://github.com/tarantool/cartridge/files/7495898/logs_5216.zip)

**Comment by yngvar-antonsson** [comment] 2021-12-17 00:12
Duplicate of #1569

**Closed by yngvar-antonsson** 2021-12-17 00:12 UTC
Labels: bug, teamS, flaky test
